/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciomodas2019;

import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author César
 */
public class Ventana extends javax.swing.JFrame {
    
    private final GestoraInformacion gestora;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        //Intentamos leer lo almacenado al cerrar el programa. En caso de que el archivo "prendas.dat" no exista, crea una nueva Gestora,
        //con "new GestoraInformacion()", estamos llamando implicitamente al método "cargarDatosIniciales"
        Object leido=GestoraAlmacenamiento.leerDatos();
        if(leido==null){
            gestora=new GestoraInformacion();
        }else{
            gestora=(GestoraInformacion) leido;
        }
        initComponents();
        tablaListado.setModel(new ModeloTabla(gestora.devolverPrendasOrdenado("CODIGO")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gb = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpNuevaPrenda = new javax.swing.JPanel();
        eCodigo = new javax.swing.JLabel();
        ctCodigo = new javax.swing.JTextField();
        eTipo = new javax.swing.JLabel();
        eProveedor1 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        cbProveedorPrenda = new javax.swing.JComboBox<>();
        bAceptarPrenda = new javax.swing.JButton();
        bCancelarPrenda = new javax.swing.JButton();
        jpTalla = new javax.swing.JPanel();
        eTalla = new javax.swing.JLabel();
        boSi = new javax.swing.JRadioButton();
        boNo = new javax.swing.JRadioButton();
        jpListadoPrenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        bEliminar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        cbOrdenListado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        eCodigo.setText("CODIGO");

        eTipo.setText("TIPO");

        eProveedor1.setText("PROVEEDOR");

        cbTipo.setModel(new DefaultComboBoxModel(TipoPrenda.values()));
        cbTipo.setSelectedItem(null);

        cbProveedorPrenda.setModel(new DefaultComboBoxModel(gestora.devolverNombresProveedor()));
        cbProveedorPrenda.setSelectedItem(null);

        bAceptarPrenda.setText("ACEPTAR");
        bAceptarPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarPrendaActionPerformed(evt);
            }
        });

        bCancelarPrenda.setText("CANCELAR");
        bCancelarPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarPrendaActionPerformed(evt);
            }
        });

        jpTalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));

        eTalla.setText("TALLA ESPECIAL");

        gb.add(boSi);
        boSi.setText("SI");

        gb.add(boNo);
        boNo.setText("NO");

        javax.swing.GroupLayout jpTallaLayout = new javax.swing.GroupLayout(jpTalla);
        jpTalla.setLayout(jpTallaLayout);
        jpTallaLayout.setHorizontalGroup(
            jpTallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTallaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(boSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(boNo)
                .addGap(14, 14, 14))
            .addGroup(jpTallaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(eTalla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTallaLayout.setVerticalGroup(
            jpTallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTallaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(eTalla)
                .addGap(18, 18, 18)
                .addGroup(jpTallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boNo)
                    .addComponent(boSi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpNuevaPrendaLayout = new javax.swing.GroupLayout(jpNuevaPrenda);
        jpNuevaPrenda.setLayout(jpNuevaPrendaLayout);
        jpNuevaPrendaLayout.setHorizontalGroup(
            jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevaPrendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNuevaPrendaLayout.createSequentialGroup()
                        .addComponent(eCodigo)
                        .addGap(48, 48, 48)
                        .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpNuevaPrendaLayout.createSequentialGroup()
                        .addComponent(jpTalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eTipo)
                            .addComponent(eProveedor1))
                        .addGap(50, 50, 50)
                        .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProveedorPrenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jpNuevaPrendaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(bAceptarPrenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCancelarPrenda)
                .addGap(64, 64, 64))
        );
        jpNuevaPrendaLayout.setVerticalGroup(
            jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevaPrendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCodigo))
                .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNuevaPrendaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eTipo)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eProveedor1)
                            .addComponent(cbProveedorPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpNuevaPrendaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpTalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jpNuevaPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptarPrenda)
                    .addComponent(bCancelarPrenda))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Nueva Prenda", jpNuevaPrenda);

        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListado);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        cbOrdenListado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CODIGO", "ESTILO", "PROVEEDOR" }));
        cbOrdenListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrdenListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpListadoPrendaLayout = new javax.swing.GroupLayout(jpListadoPrenda);
        jpListadoPrenda.setLayout(jpListadoPrendaLayout);
        jpListadoPrendaLayout.setHorizontalGroup(
            jpListadoPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListadoPrendaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(bModificar)
                .addGap(44, 44, 44))
            .addGroup(jpListadoPrendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpListadoPrendaLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(cbOrdenListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpListadoPrendaLayout.setVerticalGroup(
            jpListadoPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoPrendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(cbOrdenListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpListadoPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminar)
                    .addComponent(bModificar)))
        );

        jTabbedPane1.addTab("Listado Prenda", jpListadoPrenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarPrendaActionPerformed
        try {
            comprobar();
            procesar();
            actualizarPanelAltaPrenda();
            actualizarPanelListadoPrendas();
        } catch (MiExcepcion e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.getComponente().requestFocus();
        }
    }//GEN-LAST:event_bAceptarPrendaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        boolean escrito = GestoraAlmacenamiento.escribirDatos(gestora);
        if (!escrito) {
            JOptionPane.showMessageDialog(this, "ERROR:NO se logró almacenar la información");
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        gestora.eliminar(tablaListado.getSelectedRows());
        actualizarPanelListadoPrendas();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        VentanaModificacion hija=new VentanaModificacion(this, true);
        hija.setVisible(true);
        int seleccionada=tablaListado.getSelectedRow();
        Prenda prendaModificada = hija.devolverPrendaModificada();
        gestora.modificarDivisa(seleccionada, prendaModificada);
        this.actualizarPanelListadoPrendas();
    }//GEN-LAST:event_bModificarActionPerformed

    private void cbOrdenListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrdenListadoActionPerformed
        actualizarPanelListadoPrendas();
        tablaListado.repaint();
    }//GEN-LAST:event_cbOrdenListadoActionPerformed

    private void bCancelarPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarPrendaActionPerformed
        actualizarPanelAltaPrenda();
    }//GEN-LAST:event_bCancelarPrendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
     
    public void actualizarPanelListadoPrendas(){
        String seleccion=(String) cbOrdenListado.getSelectedItem();
        tablaListado.setModel(new ModeloTabla(gestora.devolverPrendasOrdenado(seleccion)));
    }
    
    public void actualizarPanelAltaPrenda(){
        ctCodigo.setText(null);
        gb.clearSelection();
        cbTipo.setSelectedItem(null);
        cbProveedorPrenda.setSelectedItem(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptarPrenda;
    private javax.swing.JButton bCancelarPrenda;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JRadioButton boNo;
    private javax.swing.JRadioButton boSi;
    private javax.swing.JComboBox<String> cbOrdenListado;
    private javax.swing.JComboBox<String> cbProveedorPrenda;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JLabel eCodigo;
    private javax.swing.JLabel eProveedor1;
    private javax.swing.JLabel eTalla;
    private javax.swing.JLabel eTipo;
    private javax.swing.ButtonGroup gb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpListadoPrenda;
    private javax.swing.JPanel jpNuevaPrenda;
    private javax.swing.JPanel jpTalla;
    private javax.swing.JTable tablaListado;
    // End of variables declaration//GEN-END:variables

    private void comprobar() throws MiExcepcion {
        if(!Pattern.matches("[a-zA-Z]{3}-[0-9]{2}", ctCodigo.getText())){
            throw new MiExcepcion(ctCodigo, "Hay que introducir un código de prenda compuesto por 3 letras seguidas de un guión y 2 dígitos numéricos");
        }
        if(!boSi.isSelected()&&!boNo.isSelected()){
            throw new MiExcepcion(boSi, "Debes seleccionar si es o no talla especial");
        }
        if(cbTipo.getSelectedItem()==null){
            throw new MiExcepcion(cbTipo, "Debes seleccionar el tipo de prenda");
        }
        if(cbProveedorPrenda.getSelectedItem()==null){
            throw new MiExcepcion(cbProveedorPrenda, "Debes seleccionar el proveedor de la prenda");
        }
    }

    private void procesar() {
        Prenda nuevaPrenda=new Prenda(ctCodigo.getText().toUpperCase(), (TipoPrenda) cbTipo.getSelectedItem(), boSi.isSelected(), gestora.devolverProveedor((String) cbProveedorPrenda.getSelectedItem()));
        if(gestora.agregarPrenda(nuevaPrenda)){
            JOptionPane.showMessageDialog(null, "Nueva prenda almacenada");
        }else{
            JOptionPane.showMessageDialog(null, "La prenda no ha sido almacenada, puede estar repetida");
        }
    }
    
}