/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciomodas2019;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author didi
 */
public class VentanaModificacion extends javax.swing.JDialog {

    Prenda prenda;
    GestoraInformacion gestor;
    Ventana v;
    
    public VentanaModificacion(java.awt.Frame parent, boolean modal, Prenda p, GestoraInformacion g) {
        super(parent, modal);
        this.prenda= p;
        this.gestor= g;
        initComponents();
        this.cargarFormulario();
        this.setTitle("Modificar Prenda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        eCodigo = new javax.swing.JLabel();
        ctCodigo = new javax.swing.JTextField();
        eTallaEspecial = new javax.swing.JLabel();
        eProveedor2 = new javax.swing.JLabel();
        boNo = new javax.swing.JRadioButton();
        boSi = new javax.swing.JRadioButton();
        eTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        cbProveedorPrenda = new javax.swing.JComboBox<>();
        bModificar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        eCodigo.setText("CODIGO");

        ctCodigo.setEditable(false);

        eTallaEspecial.setText("TALLA ESPECIAL");

        eProveedor2.setText("PROVEEDOR");

        buttonGroup1.add(boNo);
        boNo.setText("NO");

        buttonGroup1.add(boSi);
        boSi.setText("SI");

        eTipo.setText("TIPO");

        cbTipo.setModel(new DefaultComboBoxModel<TipoPrenda>(TipoPrenda.values()));

        cbProveedorPrenda.setModel(new DefaultComboBoxModel<String>(gestor.devolverNombresProveedor()));
        cbProveedorPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProveedorPrendaActionPerformed(evt);
            }
        });

        bModificar.setText("MODIFICAR");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bCancelar.setText("CANCELAR");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eCodigo)
                        .addGap(47, 47, 47)
                        .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eTallaEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eTipo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(eProveedor2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbProveedorPrenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bModificar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boNo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCodigo)
                    .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eTipo))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbProveedorPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eProveedor2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(eTallaEspecial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boNo)
                            .addComponent(boSi))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModificar)
                    .addComponent(bCancelar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProveedorPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProveedorPrendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProveedorPrendaActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
         if(cbProveedorPrenda.getSelectedItem()== null){
            JOptionPane.showMessageDialog(this, "Debes seleccionar el proveedor de la prenda");
            return;
        }
        if(cbTipo.getSelectedItem()== null){
            JOptionPane.showMessageDialog(this, "Debes seleccionar el tipo de prenda");
            return;
        }
        if (!this.boSi.isSelected() && !this.boNo.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar si es o no talla especial");
        }
        gestor.eliminarPrenda(ctCodigo.getText());
        Prenda pr= new Prenda(ctCodigo.getText(), (TipoPrenda)cbTipo.getSelectedItem(), this.boSi.isSelected(), gestor.devolverProveedor((String)cbProveedorPrenda.getSelectedItem()));
        gestor.agregarPrenda(pr);
        JOptionPane.showMessageDialog(this, "Nueva prenda almacenada");
        ((Ventana)this.getParent()).actualizarPaneles();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        cbProveedorPrenda.setSelectedIndex(-1);
        cbTipo.setSelectedIndex(-1);
        this.buttonGroup1.clearSelection();
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void cargarFormulario(){
        this.ctCodigo.setText(this.prenda.getCodigo());
        this.ctCodigo.setEditable(false);
        if (this.prenda.isEspecial()) {
            this.boSi.setSelected(true);
        }
        else {
            this.boNo.setSelected(true);
        }
        this.cbProveedorPrenda.setSelectedItem(this.prenda.getElProveedor().getNombre());
        this.cbTipo.setSelectedItem(this.prenda.getTipo());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bModificar;
    private javax.swing.JRadioButton boNo;
    private javax.swing.JRadioButton boSi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbProveedorPrenda;
    private javax.swing.JComboBox<TipoPrenda> cbTipo;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JLabel eCodigo;
    private javax.swing.JLabel eProveedor2;
    private javax.swing.JLabel eTallaEspecial;
    private javax.swing.JLabel eTipo;
    // End of variables declaration//GEN-END:variables
}
