package ejerciciomodas2019;


import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafa
 */
public class VentanaModificacion extends javax.swing.JDialog {

    Prenda laPrenda;
    GestoraInformacion gestor;
    Ventana laVentana;
    /**
     * Creates new form VentanaModificacion
     */
    public VentanaModificacion(java.awt.Frame parent, boolean modal, Prenda p, GestoraInformacion g) {
        super(parent, modal);
        this.laPrenda = p;
        this.gestor = g;
        initComponents();
        this.cargarFormulario();
        this.setTitle("Modificar Prenda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gb = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ctCodigo = new javax.swing.JTextField();
        boSi = new javax.swing.JRadioButton();
        boNo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        cbProveedorPrenda = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CODIGO");

        ctCodigo.setEditable(false);

        gb.add(boSi);
        boSi.setText("SI");

        gb.add(boNo);
        boNo.setText("NO");

        jLabel2.setText("TALLA ESPECIAL");

        jLabel3.setText("TIPO");

        jLabel4.setText("PROVEEDOR");

        cbTipo.setModel(new DefaultComboBoxModel<TipoPrenda>(TipoPrenda.values()));

        cbProveedorPrenda.setModel(new DefaultComboBoxModel<String>(gestor.devolverNombresProveedor()));

        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(57, 57, 57)
                                        .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(boSi)
                                                .addGap(18, 18, 18)
                                                .addComponent(boNo)))
                                        .addGap(149, 149, 149)
                                        .addComponent(cbProveedorPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boSi)
                    .addComponent(boNo)
                    .addComponent(jLabel4)
                    .addComponent(cbProveedorPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(cbProveedorPrenda.getSelectedItem()== null){
            JOptionPane.showMessageDialog(this, "Debes seleccionar el proveedor de la prenda");
            return;
        }
        if(cbTipo.getSelectedItem()== null){
            JOptionPane.showMessageDialog(this, "Debes seleccionar el tipo de prenda");
            return;
        }
        if (!this.boSi.isSelected() && !this.boNo.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar si es o no talla especial");
        }
        gestor.eliminarPrenda(ctCodigo.getText());
        Prenda pr= new Prenda(ctCodigo.getText(), (TipoPrenda)cbTipo.getSelectedItem(), this.boSi.isSelected(), gestor.devolverProveedor((String)cbProveedorPrenda.getSelectedItem()));
        gestor.agregarPrenda(pr);
        JOptionPane.showMessageDialog(this, "Nueva prenda almacenada");
        ((Ventana)this.getParent()).actualizarPaneles();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cbProveedorPrenda.setSelectedIndex(-1);
        cbTipo.setSelectedIndex(-1);
        this.gb.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void cargarFormulario(){
         this.ctCodigo.setText(this.laPrenda.getCodigo());
        this.ctCodigo.setEditable(false);
        if (this.laPrenda.isEspecial()) {
            this.boSi.setSelected(true);
        }
        else {
            this.boNo.setSelected(true);
        }
        this.cbProveedorPrenda.setSelectedItem(this.laPrenda.getElProveedor().getNombre());
        this.cbTipo.setSelectedItem(this.laPrenda.getTipo());
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boNo;
    private javax.swing.JRadioButton boSi;
    private javax.swing.JComboBox<String> cbProveedorPrenda;
    private javax.swing.JComboBox<TipoPrenda> cbTipo;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.ButtonGroup gb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
