/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciomodas2019;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tarod
 */
public class VentanaModificar extends javax.swing.JDialog {

    private GestoraInformacion gestora;
    private Prenda laPrenda;
    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar(java.awt.Frame parent, Prenda p, boolean modal) {
        super(parent, modal);
        this.gestora = GestoraInformacion.getInstance();
        this.laPrenda = p;
        initComponents();
        ctCodigo.setText(laPrenda.getCodigo());
        cbTipo.setSelectedItem(laPrenda.getTipo());
        cbProveedor.setSelectedItem(laPrenda.getElProveedor().getNombre());
        if(laPrenda.isEspecial()) {
            jrTallaEspecial.setSelected(true);
        } else {
            jrNoTallaEspecial.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rGrupoTallaEspecial = new javax.swing.ButtonGroup();
        jpModificarPrenda = new javax.swing.JPanel();
        ctCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        cbProveedor = new javax.swing.JComboBox<>();
        bCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jrTallaEspecial = new javax.swing.JRadioButton();
        jrNoTallaEspecial = new javax.swing.JRadioButton();
        bAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ctCodigo.setEditable(false);

        jLabel1.setText("CODIGO");

        jLabel2.setText("TIPO");

        jLabel3.setText("PROVEEDOR");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(TipoPrenda.values()));
        cbTipo.setSelectedItem(null);

        cbProveedor.setModel(new javax.swing.DefaultComboBoxModel(gestora.devolverNombresProveedor()));
        cbProveedor.setSelectedItem(null);
        cbProveedor.setToolTipText("");

        bCancelar.setText("CANCELAR");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("TALLA ESPECIAL");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setMaximumSize(new java.awt.Dimension(192, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(192, 16));
        jLabel4.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(jLabel4, gridBagConstraints);

        rGrupoTallaEspecial.add(jrTallaEspecial);
        jrTallaEspecial.setText("SI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(jrTallaEspecial, gridBagConstraints);

        rGrupoTallaEspecial.add(jrNoTallaEspecial);
        jrNoTallaEspecial.setText("NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(jrNoTallaEspecial, gridBagConstraints);

        bAceptar.setText("ACEPTAR");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpModificarPrendaLayout = new javax.swing.GroupLayout(jpModificarPrenda);
        jpModificarPrenda.setLayout(jpModificarPrendaLayout);
        jpModificarPrendaLayout.setHorizontalGroup(
            jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModificarPrendaLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpModificarPrendaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpModificarPrendaLayout.createSequentialGroup()
                        .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpModificarPrendaLayout.createSequentialGroup()
                                .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bAceptar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpModificarPrendaLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45)
                                        .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(83, 215, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModificarPrendaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(47, 47, 47)))
                        .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbProveedor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))))
        );
        jpModificarPrendaLayout.setVerticalGroup(
            jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModificarPrendaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpModificarPrendaLayout.createSequentialGroup()
                        .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jpModificarPrendaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jpModificarPrendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpModificarPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpModificarPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            comprobar();
            procesar();
            limpiar();
            this.setVisible(false);
        } catch (MiExcepcion ex) {
            javax.swing.JComponent elComponente = ex.getComponente();
            JOptionPane.showMessageDialog(this, ex.getMessage());
            elComponente.requestFocus();

            if(elComponente instanceof javax.swing.JTextField) {
                ((javax.swing.JTextField) elComponente).selectAll();
            }
            else if(elComponente instanceof javax.swing.JComboBox) {
                ((javax.swing.JComboBox) elComponente).setSelectedItem(null);
            }
            else if(elComponente instanceof javax.swing.JRadioButton) {
                ((javax.swing.JPanel)
                    ((javax.swing.JRadioButton)
                        elComponente).getParent()).setBorder(
                    javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED)
                );
            }
        } catch (Throwable ex) {
            Logger.getLogger(VentanaModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpModificarPrenda;
    private javax.swing.JRadioButton jrNoTallaEspecial;
    private javax.swing.JRadioButton jrTallaEspecial;
    private javax.swing.ButtonGroup rGrupoTallaEspecial;
    // End of variables declaration//GEN-END:variables

    private void comprobar() throws MiExcepcion {
        Object objetoTipo = cbTipo.getSelectedItem();
        Object objetoProveedor = cbProveedor.getSelectedItem();
        
        if(objetoTipo == null) {
            throw new MiExcepcion(cbTipo, "Debe seleccionar un Tipo de prenda.");
        }
        if(objetoProveedor == null) {
            throw new MiExcepcion(cbProveedor, "Debe seleccionar un Proveedor.");
        }
        if(rGrupoTallaEspecial.getSelection() == null) {
            throw new MiExcepcion(jrTallaEspecial, "Debe seleccionar si es o no Talla Especial.");
        }
    }

    private void procesar() {
        TipoPrenda tipo = (TipoPrenda) cbTipo.getSelectedItem();
        boolean esEspecial = jrTallaEspecial.isSelected();
        Proveedor proveedor = gestora.devolverProveedor(cbProveedor.getSelectedItem().toString());
        
        laPrenda.setTipo(tipo);
        laPrenda.setEspecial(esEspecial);
        laPrenda.setElProveedor(proveedor);
    }

    private void limpiar() {
//        Ventana.limpiarPanel(jpModificarPrenda);
        cbTipo.setSelectedItem(null);
        cbProveedor.setSelectedItem(null);
        rGrupoTallaEspecial.clearSelection();
    }
}
